name: product_crud_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  provider: ^6.1.5
  intl: ^0.20.2
  syncfusion_flutter_pdf: ^30.2.4
  csv: ^6.0.0
  easy_debounce: ^2.0.3
  dropdown_button2: ^2.3.9
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
